readme.md
Please consider including Taskade!
=> Added Taskade

readme.md
Please consider including Enpass (password manager)!
=> Add Enpass

readme.md
Hi, very nice list. Please consider adding PhotoMD and PhotoMD-lite to this awesome list. _Also added missing link to Image Editors in index._
=> Add PhotoMD

readme.md
For your consideration / curation, Moo!
```
(__)
/   @@      ______
|  /\_|     |      \
|  |___     |       |
|   ---@    |_______|
|  |   ----   |    |
|  |_____
*____/|________|
CompuCow After an All-niter
```
=> Add a few of my mac apps

readme.md
Thanks for making this list! :)
=> 📝 Add Raycast

readme.md
Just fixing a typo in the table of contents.
=> Fix terminal link in the table of contents

readme.md
Link - https://presentify.compzets.com/
=> New Presentify app!

readme.md
Definitely one of my most used applications. I put this under menu bar apps but if there is a more suitable place, let me know.
=> Added Amphetamine to list

readme.md
Raycast is already present in the list and both of them had same URL
=> Removed duplicate app name - Raycast.

readme.md
- Edit typora to paid app (now it's $14.99 with 15 days free trial).
- Add Syntax highlight and QLMarkdown.
=> Edit typora & add quicklook plugin

readme.md
Hi,
Sidebar is a modern MacOS Dock replacement that feels really intuitive to use and adds tons of features compared to the standard MacOS Dock.
Please consider adding it.
Thanks and all the best!
=> Add Sidebar

readme.md
=> Add No More Black Bars

readme.md
Please help to review HelperX app.
HelperX - All-in-one Utility and Productivity Software for macOS.
=> HelperX - All-in-one Utility and Productivity Software for macOS.

readme.md
This is a lightweight code editor like Xcode
=> Added CodeEdit

readme.md
This is one of my favourite apps!
=> Added CleanMyMac X

readme.md
I added MacGPT in the machine learning section
=> Added MacGPT

readme.md
Hello @phmullins, I added MindMac - A feature-rich & privacy-first native ChatGPT app to use OpenAI, Azure OpenAI, Anthropic Claude, OpenRouter all in one place. Please help to review this PR. Thank you!
=> Add MindMac to productivity section

readme.md
Hey @phmullins!
I would like to add the Lasso app to the list. A [lot](https://www.producthunt.com/products/lasso-window-wanager-for-macos/reviews) of people believe it's an awesome app so I think it deserves it's place here :)
=> Add Lasso - window manager

readme.md
Cursor is a recently launched editor based on vscode with additional ChatGPT integration. I wanted to introduce it to you because it is very powerful.
=> Add Cursor: The AI-first Code Editor

readme.md
Hello, @phmullins! [Smotrite](https://github.com/Lukentui/smotrite-app) is ux-focused app, which show you actual system information and, in the future it will have task manager functionality. Please, merge this PR. Thank you in advance :)
=> Added Smotrite app

readme.md
=> Add Tart virtualization 

readme.md
Added this godlike project that opensource and free.
=> Added Syncthing

readme.md
Add PlugNPlayMac on System Tools
=> Update readme.md - Add PlugNPlayMac on System Tools

readme.md
Hey @phmullins,
RewriteBar is a native macOS app that adds writing and text transformation features with the help of AI. You can select text in any application and send it to OpenAI, which will then improve it based on your selected action. You can also create your own actions for custom workflows.
Website: https://rewritebar.com
Let me know if I should change anything :)
=> Add RewriteBar

readme.md
This PR serves to add DockDoor and NotchNook to the readme.md
=> Add DockDoor and NotchNook to readme

readme.md
Added "File Management > Folders"
=> Added Folders to File Management

readme.md
Thanks for the awesome list. I'm the developer of Dropzone and I noticed Dropzone was missing a description so have added one 😄
=> Fix Dropzone missing description

readme.md
=> Added FileMinutes

readme.md
=> Added Klack & Alcove
